# SQLite datasource
spring.datasource.url=jdbc:sqlite:beer.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=student
spring.rabbitmq.password=student

# Queue din care BeerDAOMicroservice citeste comenzile de la CLI
beerapp.rabbitmq.queue=beerapp.queue1

# Exchange si routing key pe care BeerDAOMicroservice trimite raspunsurile inapoi la CLI
beerapp.rabbitmq.exchange=beerapp.direct
beerapp.rabbitmq.routingkey=beerapp.routingkey

# Port server (implicit 8080)
server.port=8080
