spring.application.name=CacheMicroservice
spring.datasource.url=jdbc:sqlite:cache.db
spring.datasource.driver-class-name=org.sqlite.JDBC
server.port=8081

library.service.url=http://localhost:8080
merkle.service.url=http://localhost:8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=student
spring.rabbitmq.password=student